### ISSUE TITLE
Sync with CouchDB → 404 errors

### ISSUE THREAD

**Issue by Chostakovitch** [agateblue/tempo#10]
Hi,

First of all thanks for taking the time to thoroughly document that tool for others. It is already really useful to me.

The synchronization features started to throw errors, but I only realized it when try to force sync and saw a `not found` message.
Here's a screenshot of what happens :

![](https://pic.chosto.me/uploads/big/1dd6785367ca0cf6931de70069230ff4.jpg)

Maybe it's a problem on my side but I have no clue to debug it. Do you have any idea ?

Thanks and have a nice day.

**Comment by agateblue** [comment]
Hey there!

From the screenshot, it seems that the request is sent without the Database name in the URL (domain.tld//__revs_diff).

I just realize I probably didn't documented it anywhere but can you check that the `CouchDB URL` settings includes the database name? For instance `https://couchdb/tempo` if your DB name is Tempo.

**Comment by Chostakovitch** [comment]
Aaaaaand... that was that. I probably could have guess myself... Thanks a lot for your assistance. :)
