### ISSUE TITLE
Time display in diary

### ISSUE THREAD

**Issue by dskrad** [agateblue/tempo#23]
I noticed a bug with time display. For my timezone (eastern US), if I enter a diary entry beyond 7 PM, then the calculated time displaying in the diary is a negative number (-1, -2, -3, etc). I think there is a bug in this function:

https://github.com/agateblue/tempo/blob/2ee964724920fedecc98c4fe9e2fb6a7cc460a13/src/utils.js#L298

Why not use built-in javascript function for displaying local time:

    date.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit', hourCycle: 'h24' }))

**Comment by agateblue** [comment]
Thanks, I wasn't aware there was such a simple way to do it!
