### ISSUE TITLE
Bug in annotation parsing/edit

### ISSUE THREAD

**Issue by entropyqueen** [agateblue/tempo#45]
Quand on édite un tag annotation, le contenu n'est pas re-parsé, il faut nécessairement l'éditer dans les champs en dessous. Je pense que ça ferai sens d'avoir un re-parsing de l'entrée.

Par exemple, je veux créer 2 annotations:
![tempo_annotation_bug1](https://user-images.githubusercontent.com/2721112/212545653-1023d9d3-aaa5-4682-baa3-833cf57400ee.png)

Je me suis ratée, ça donne ça:
![tempo_annotation_bug2](https://user-images.githubusercontent.com/2721112/212545677-5230ec0d-12b5-49f6-81ed-c03b7f9e6e84.png)

Donc j'édite pour remettre le retour à la ligne, ce qui donne:
![tempo_annotation_bug3](https://user-images.githubusercontent.com/2721112/212545748-6341c27e-5635-4e68-969c-097a5297b0cb.png)

Je pense qu'il serait préférable que la valeur du tag soit prise jusqu'au \n ou s'arrêter avant si il y a une autre annotation ? Et sinon juste pour l'édition, re-parser l'entrée pour corriger les valeurs.

**Comment by agateblue** [comment]
Il y avait en fait deux bugs:

1. Un souci dans le parsing, corrigé
2. Un comportement que j'avais introduit, qui affichait les champs de formulaires correspondant pour les annotations lors de l'édition d'une entrée. Sauf que c'était les données du formulaire qui prenaient le dessus, et pas celles des annotations dans le corps de l'entrée. J'ai retiré cette logique de formulaire pour les annotatiors libres, sans formulaires, c'est plus simple.
